### ISSUE TITLE
Requires BRug which is only working on R 4.2 or older

### ISSUE THREAD

**Issue by erikstricker** [neurogenomics/MungeSumstats#178]
**Bug:**
When installing MungeSumstats, it requires BRug. However, support or updates for BRug have been discontinued and the code calls a 32-bit makefile. R 4.3 removed 32-bit support for Windows 11 64-bit and BRug 

**Error message:**
```
* installing *source* package 'BRugs' ...
** package 'BRugs' successfully unpacked and MD5 sums checked
** using staged installation
** libs
  running 'src/Makefile.win' ...
Makefile.win:1: C:/PROGRA~1/R/R-42~1.2/etc/i386/Makeconf: No such file or directory
make: *** No rule to make target 'C:/PROGRA~1/R/R-42~1.2/etc/i386/Makeconf'.  Stop.
ERROR: compilation failed for package 'BRugs'
* removing 'C:/Users/antho/AppData/Local/R/win-library/4.2.2/BRugs'
Warning in install.packages :
  installation of package ‘BRugs’ had non-zero exit status
```

**Workaround:**
The workaround seems to be to install R 4.1.2 together with Rtools.

**Comment by Al-Murphy** [comment]
This is odd, what version of MSS are you using? It has been passing on the current build and Dev build of bioconductor across all os tested. So I don't think I can replicate the issue? I would say try installing the latest version of MSS and then if that fails, try the bioconductor docker image to run it? Let me know how that goes!

**Comment by erikstricker** [comment]
MSS as in MungeSumstats?

**Comment by Al-Murphy** [comment]
Yep exactly, sorry!

**Comment by erikstricker** [comment]
I just instakked MungeSumstats_1.10.1. I had to delete BRugs from my R library and all of a sudden it works.

Sorry for the inconvenience.

**Comment by Al-Murphy** [comment]
No worries, glad you got it working!!
